### ISSUE TITLE
data pre-processing

### ISSUE THREAD

**Issue by RenPengFei0** [jcausey-astate/ai_campus_kits19#1]
Hello. I would like to ask, could you kindly inform me which file contains the code for CT image preprocessing? I didn't find anything related to it in the code you posted. I would greatly appreciate it if you could reply to me.

**Comment by jcausey-astate** [comment]
The code for caching the axial slices is in "build_slice_cache.py".

The preprocessing code for standardizing the images is in two places, depending on whether you are in the training or inferece phase:
* In training (and during the caching step), image standardization is done by the `standardize_HU()` method (kits_volume_utils.py:177), called by the `load_nifti_volume()` function (kits_volume_utils.py:191).
* For inference, the image standardization (window threshold and conversion to range [0,1]) happens in the `standardize_HU()` method of the `Orchestra` class (orchestra.py:145), normally during loading with the `load_nifti()` method (orchestra.py:79).

**Comment by RenPengFei0** [comment]
Thank you for your reply.

---- Replied Message ----
| From | Jason L ***@***.***> |
| Date | 12/06/2024 23:57 |
| To | jcausey-astate/ai_campus_kits19 ***@***.***> |
| Cc | RenPengFei0 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [jcausey-astate/ai_campus_kits19] data pre-processing (Issue #1) |

The code for caching the axial slices is in "build_slice_cache.py".

The preprocessing code for standardizing the images is in two places, depending on whether you are in the training or inferece phase:

In training (and during the caching step), image standardization is done by the standardize_HU() method (kits_volume_utils.py:177), called by the load_nifti_volume() function (kits_volume_utils.py:191).
For inference, the image standardization (window threshold and conversion to range [0,1]) happens in the standardize_HU() method of the Orchestra class (orchestra.py:145), normally during loading with the load_nifti() method (orchestra.py:79).
